export function createMockPhysiologicalData() {
  const now = new Date();
  const iso = (d) => new Date(d).toISOString();

  const patients = [
    {
      id: 'pt-1001',
      name: 'John Doe',
      mrn: 'MRN-001',
      dob: '1985-05-15',
      age: 39,
      gender: 'M',
    },
    {
      id: 'pt-1002',
      name: 'Mary Johnson',
      mrn: 'MRN-002',
      dob: '1992-08-02',
      age: 33,
      gender: 'F',
    },
    {
      id: 'pt-1003',
      name: 'Ahmed Khan',
      mrn: 'MRN-003',
      dob: '1978-11-22',
      age: 47,
      gender: 'M',
    },
  ];

  const orders = [
    {
      id: 'phys-9001',
      patientId: 'pt-1001',
      testName: '12-Lead EKG',
      testType: 'EKG',
      department: 'Cardiology',
      orderDateTime: iso(now),
      status: 'Pending',
      priority: 'Routine',
      orderingProvider: 'Dr. Jane Smith',
      isOutside: false,
      lastUpdatedAt: iso(now),
    },
    {
      id: 'phys-9002',
      patientId: 'pt-1002',
      testName: 'Spirometry',
      testType: 'Pulmonary Function',
      department: 'Pulmonology',
      orderDateTime: iso(now),
      status: 'In Progress',
      priority: 'Urgent',
      orderingProvider: 'Dr. John Williams',
      isOutside: false,
      lastUpdatedAt: iso(now),
    },
    {
      id: 'phys-9003',
      patientId: 'pt-1002',
      testName: 'Stress Test (Treadmill)',
      testType: 'Cardiac Stress',
      department: 'Cardiology',
      orderDateTime: iso(now),
      status: 'Completed',
      priority: 'Routine',
      orderingProvider: 'Dr. John Williams',
      isOutside: false,
      lastUpdatedAt: iso(now),
    },
    {
      id: 'phys-9004',
      patientId: 'pt-1003',
      testName: 'EEG',
      testType: 'Neurological',
      department: 'Neurology',
      orderDateTime: iso(now),
      status: 'Scheduled',
      priority: 'Stat',
      orderingProvider: 'Dr. Jane Smith',
      isOutside: false,
      lastUpdatedAt: iso(now),
    },
    {
      id: 'phys-9005',
      patientId: 'pt-1001',
      testName: 'EKG (Outside)',
      testType: 'EKG',
      department: 'External',
      orderDateTime: iso(now),
      status: 'Results Pending',
      priority: 'Routine',
      orderingProvider: 'Outside Facility',
      isOutside: true,
      externalFacility: 'City Heart Center',
      lastUpdatedAt: iso(now),
    },
    {
      id: 'phys-9006',
      patientId: 'pt-1003',
      testName: 'PFT (Outside)',
      testType: 'Pulmonary Function',
      department: 'External',
      orderDateTime: iso(now),
      status: 'Received',
      priority: 'Routine',
      orderingProvider: 'Outside Facility',
      isOutside: true,
      externalFacility: 'Metro Pulmonary Lab',
      lastUpdatedAt: iso(now),
    },
  ];

  return { patients, orders };
}
