export const MOCK_NURSES = [
  { id: 'N001', name: 'Johnson, RN' },
  { id: 'N002', name: 'Williams, RN' },
];

export const MOCK_PATIENTS = [
  {
    id: 'pt-1',
    mrn: '10018472',
    name: 'Doe, John A.',
    dob: '1985-05-15',
    age: 39,
    sex: 'M',
    acuity: 'ESI-2',
    chiefComplaint: 'Chest pain, SOB',
    room: 'ED-101',
    nurse: 'Johnson, RN',
    nurseId: 'N001',
    provider: 'Smith, MD',
    providerId: 'P001',
    vitals: { bp: '120/80', hr: 72, temp: '98.6', spo2: '98%' },
    nursingStatus: 'Ready for Provider',
    checkInTime: '2025-01-15T08:30:00',
    timeInStatus: 42,
    pendingTasks: '—',
    notes: '',
    flags: ['Interpreter'],
  },
  {
    id: 'pt-2',
    mrn: '10019203',
    name: 'Smith, Jane M.',
    dob: '1990-08-22',
    age: 34,
    sex: 'F',
    acuity: 'ESI-3',
    chiefComplaint: 'Fever, headache',
    room: 'ED-102',
    nurse: 'Williams, RN',
    nurseId: 'N002',
    provider: null,
    providerId: null,
    vitals: null,
    nursingStatus: 'Vitals Pending',
    checkInTime: '2025-01-15T09:15:00',
    timeInStatus: 18,
    pendingTasks: 'Vitals · Assessment',
    notes: '',
    flags: [],
  },
  {
    id: 'pt-3',
    mrn: '10017891',
    name: 'Brown, Robert K.',
    dob: '1978-12-03',
    age: 46,
    sex: 'M',
    acuity: 'ESI-2',
    chiefComplaint: 'Abdominal pain',
    room: 'ED-103',
    nurse: 'Johnson, RN',
    nurseId: 'N001',
    provider: 'Smith, MD',
    providerId: 'P001',
    vitals: { bp: '130/85', hr: 95, temp: '99.1', spo2: '97%' },
    nursingStatus: 'With Provider',
    checkInTime: '2025-01-15T07:00:00',
    timeInStatus: 95,
    pendingTasks: '—',
    notes: 'NPO',
    flags: ['NPO'],
  },
  {
    id: 'pt-4',
    mrn: '10020144',
    name: 'Garcia, Maria L.',
    dob: '1982-03-10',
    age: 42,
    sex: 'F',
    acuity: 'ESI-4',
    chiefComplaint: 'Sore throat',
    room: 'ED-104',
    nurse: 'Johnson, RN',
    nurseId: 'N001',
    provider: null,
    providerId: null,
    vitals: { bp: '118/72', hr: 78, temp: '98.9', spo2: '99%' },
    nursingStatus: 'Assessment Done',
    checkInTime: '2025-01-15T10:00:00',
    timeInStatus: 25,
    pendingTasks: '—',
    notes: '',
    flags: [],
  },
  {
    id: 'pt-5',
    mrn: '10021567',
    name: 'Lee, David T.',
    dob: '1995-11-20',
    age: 29,
    sex: 'M',
    acuity: 'ESI-4',
    chiefComplaint: 'Ankle injury',
    room: 'ED-105',
    nurse: 'Williams, RN',
    nurseId: 'N002',
    provider: null,
    providerId: null,
    vitals: null,
    nursingStatus: 'Check-In',
    checkInTime: '2025-01-15T10:45:00',
    timeInStatus: 8,
    pendingTasks: 'Vitals · Assessment',
    notes: '',
    flags: [],
  },
  {
    id: 'pt-6',
    mrn: '10016988',
    name: 'Wilson, Sarah E.',
    dob: '1970-07-08',
    age: 54,
    sex: 'F',
    acuity: 'ESI-3',
    chiefComplaint: 'DM follow-up',
    room: 'ED-106',
    nurse: 'Williams, RN',
    nurseId: 'N002',
    provider: 'Chen, MD',
    providerId: 'P002',
    vitals: { bp: '125/82', hr: 70, temp: '98.4', spo2: '98%' },
    nursingStatus: 'Discharged/Cleanup',
    checkInTime: '2025-01-15T08:00:00',
    timeInStatus: 120,
    pendingTasks: 'Room cleanup',
    notes: 'DC 11:00',
    flags: [],
  },
];

export const BOARD_COLUMNS = [
  { key: 'status', label: 'Status', defaultVisible: true, width: 'w-[148px]' },
  { key: 'patient', label: 'Patient', defaultVisible: true, width: 'min-w-[200px]' },
  { key: 'mrn', label: 'MRN', defaultVisible: true, width: 'w-[100px]' },
  { key: 'ageSex', label: 'Age/Sex', defaultVisible: true, width: 'w-[72px]' },
  { key: 'acuity', label: 'Acuity', defaultVisible: true, width: 'w-[64px]' },
  { key: 'room', label: 'Room', defaultVisible: true, width: 'w-[80px]' },
  { key: 'chiefComplaint', label: 'Chief Complaint', defaultVisible: true, width: 'min-w-[160px]' },
  { key: 'nurse', label: 'Nurse', defaultVisible: true, width: 'w-[120px]' },
  { key: 'provider', label: 'Provider', defaultVisible: true, width: 'w-[110px]' },
  { key: 'vitals', label: 'Vitals', defaultVisible: true, width: 'w-[140px]' },
  { key: 'checkIn', label: 'Arrival', defaultVisible: true, width: 'w-[72px]' },
  { key: 'timeInStatus', label: 'Min in Status', defaultVisible: true, width: 'w-[88px]' },
  { key: 'pendingTasks', label: 'Pending', defaultVisible: true, width: 'min-w-[120px]' },
  { key: 'notes', label: 'Comments', defaultVisible: false, width: 'min-w-[100px]' },
  { key: 'action', label: '', defaultVisible: true, width: 'w-[72px]' },
];

/** Workflow status styling — uses app theme tokens */
export const NURSING_STATUS_STYLE = {
  'Check-In': {
    label: 'Check In',
    stripe: 'bg-muted-foreground',
    pill: 'bg-muted text-foreground border-border',
  },
  'Vitals Pending': {
    label: 'Vitals Pending',
    stripe: 'bg-chart-3',
    pill: 'bg-chart-3/15 text-foreground border-chart-3/50',
  },
  'Assessment Done': {
    label: 'Assessment Done',
    stripe: 'bg-chart-2',
    pill: 'bg-chart-2/15 text-foreground border-chart-2/50',
  },
  'Ready for Provider': {
    label: 'Ready for Provider',
    stripe: 'bg-chart-3',
    pill: 'bg-accent text-accent-foreground border-primary/25',
  },
  'With Provider': {
    label: 'With Provider',
    stripe: 'bg-primary',
    pill: 'bg-primary/10 text-primary border-primary/30',
  },
  'Discharged/Cleanup': {
    label: 'Discharged',
    stripe: 'bg-muted-foreground/60',
    pill: 'bg-secondary text-secondary-foreground border-border',
  },
};

export const BOARD_TABS = [
  { id: 'all', label: 'All Patients' },
  { id: 'my-patients', label: 'My Patients' },
  { id: 'vitals-pending', label: 'Vitals Pending' },
  { id: 'ready-for-provider', label: 'Ready for Provider' },
  { id: 'completed', label: 'Completed' },
];

export const PAGE_SIZES = [25, 50, 100];
