export const TELEPHONIC_FIELDS = [
  { key: 'callDate', label: 'Call date', type: 'date' },
  { key: 'callTime', label: 'Call time', type: 'time' },
  {
    key: 'direction',
    label: 'Call direction',
    type: 'select',
    options: ['Inbound', 'Outbound'],
  },
  { key: 'callerName', label: 'Caller / Contact name', type: 'text', placeholder: 'Name of person spoken with' },
  {
    key: 'relationship',
    label: 'Relationship to patient',
    type: 'select',
    options: ['Self', 'Spouse', 'Parent', 'Child', 'Caregiver', 'Other'],
  },
  { key: 'phoneNumber', label: 'Phone number', type: 'text', placeholder: '+1…' },
  {
    key: 'reasonForCall',
    label: 'Reason for call',
    type: 'textarea',
    rows: 2,
    span: 2,
    placeholder: 'Why the patient or contact called / was contacted',
  },
  {
    key: 'discussion',
    label: 'Discussion summary',
    type: 'textarea',
    rows: 4,
    span: 2,
    placeholder: 'What was discussed during the call',
  },
  {
    key: 'adviceGiven',
    label: 'Advice / instructions given',
    type: 'textarea',
    rows: 3,
    span: 2,
    placeholder: 'Clinical advice, triage guidance, or instructions provided',
  },
  {
    key: 'followUp',
    label: 'Follow-up needed',
    type: 'textarea',
    rows: 2,
    span: 2,
    placeholder: 'Callback, appointment, message to provider, etc.',
  },
  {
    key: 'urgency',
    label: 'Urgency',
    type: 'select',
    options: ['Routine', 'Urgent', 'Emergent'],
  },
];

export const PROGRESS_FIELDS = [
  {
    key: 'intervalHistory',
    label: 'Interval history',
    type: 'textarea',
    rows: 4,
    span: 2,
    placeholder: 'Changes since last note: symptoms, adherence, response to treatment',
  },
  {
    key: 'objective',
    label: 'Objective / findings',
    type: 'textarea',
    rows: 3,
    span: 2,
    placeholder: 'Exam findings, vitals reviewed, new results',
  },
  {
    key: 'assessment',
    label: 'Assessment / status',
    type: 'textarea',
    rows: 3,
    span: 2,
    placeholder: 'Clinical status update for active problems',
  },
  {
    key: 'plan',
    label: 'Plan / changes',
    type: 'textarea',
    rows: 3,
    span: 2,
    placeholder: 'Medication changes, orders, counseling, next steps',
  },
  {
    key: 'responseToTreatment',
    label: 'Response to treatment',
    type: 'textarea',
    rows: 2,
    span: 2,
    placeholder: 'Improved / unchanged / worsened — details',
  },
];

export const PROCEDURE_FIELDS = [
  { key: 'procedureName', label: 'Procedure name', type: 'text', placeholder: 'e.g., Laceration repair' },
  { key: 'cptCode', label: 'CPT / procedure code', type: 'text', placeholder: 'Optional code' },
  {
    key: 'indication',
    label: 'Indication',
    type: 'textarea',
    rows: 2,
    span: 2,
    placeholder: 'Clinical reason for the procedure',
  },
  {
    key: 'consent',
    label: 'Consent',
    type: 'select',
    options: ['Obtained — verbal', 'Obtained — written', 'Emergent — implied', 'Not applicable'],
  },
  {
    key: 'anesthesia',
    label: 'Anesthesia / analgesia',
    type: 'text',
    placeholder: 'Local, none, sedation, etc.',
  },
  {
    key: 'technique',
    label: 'Technique / description',
    type: 'textarea',
    rows: 4,
    span: 2,
    placeholder: 'Step-by-step description of what was performed',
  },
  {
    key: 'findings',
    label: 'Findings',
    type: 'textarea',
    rows: 3,
    span: 2,
    placeholder: 'Intra-procedure findings',
  },
  {
    key: 'complications',
    label: 'Complications',
    type: 'textarea',
    rows: 2,
    span: 2,
    placeholder: 'None, or describe',
    defaultValue: 'None',
  },
  {
    key: 'specimens',
    label: 'Specimens / implants',
    type: 'textarea',
    rows: 2,
    span: 2,
    placeholder: 'Labs sent, devices placed, etc.',
  },
  {
    key: 'postInstructions',
    label: 'Post-procedure instructions',
    type: 'textarea',
    rows: 3,
    span: 2,
    placeholder: 'Wound care, activity, return precautions',
  },
];

export const COMMUNICATION_FIELDS = [
  {
    key: 'commType',
    label: 'Communication type',
    type: 'select',
    options: [
      'Patient',
      'Family / caregiver',
      'External provider',
      'Internal care team',
      'Insurance / payer',
      'Other',
    ],
  },
  {
    key: 'method',
    label: 'Method',
    type: 'select',
    options: ['Phone', 'Portal message', 'In person', 'Email', 'Fax', 'Video'],
  },
  {
    key: 'participants',
    label: 'Participants',
    type: 'text',
    placeholder: 'Names / roles involved',
    span: 2,
  },
  {
    key: 'topic',
    label: 'Topic',
    type: 'text',
    placeholder: 'Subject of the communication',
    span: 2,
  },
  {
    key: 'summary',
    label: 'Summary',
    type: 'textarea',
    rows: 4,
    span: 2,
    placeholder: 'What was communicated',
  },
  {
    key: 'outcome',
    label: 'Outcome / action items',
    type: 'textarea',
    rows: 3,
    span: 2,
    placeholder: 'Decisions made, tasks assigned, follow-up',
  },
];

export const BLANK_FIELDS = [
  {
    key: 'noteTitle',
    label: 'Note title',
    type: 'text',
    placeholder: 'Short title for this note',
    span: 2,
  },
  {
    key: 'category',
    label: 'Category (optional)',
    type: 'select',
    options: ['General', 'Nursing', 'Administrative', 'Care coordination', 'Other'],
  },
  {
    key: 'body',
    label: 'Note',
    type: 'textarea',
    rows: 10,
    span: 2,
    placeholder: 'Free-text clinical note…',
  },
];
