export function createMockRadiologyData() {
  const now = new Date();
  const iso = (d) => new Date(d).toISOString();

  const patients = [
    {
      id: 'p-1001',
      name: 'John Doe',
      mrn: 'MRN-001',
      dob: '1985-05-15',
      age: 39,
      gender: 'M',
      admission: {
        erId: 'ER-24011',
        chiefComplaint: 'Headache',
        arrivalMethod: 'Walk-in',
        status: 'Triage',
      },
    },
    {
      id: 'p-1002',
      name: 'Mary Johnson',
      mrn: 'MRN-002',
      dob: '1992-08-02',
      age: 33,
      gender: 'F',
      admission: {
        erId: 'ER-24012',
        chiefComplaint: 'Abdominal pain',
        arrivalMethod: 'Ambulance',
        status: 'Roomed',
      },
    },
    {
      id: 'p-1003',
      name: 'Ahmed Khan',
      mrn: 'MRN-003',
      dob: '1978-11-22',
      age: 47,
      gender: 'M',
      admission: {
        erId: 'ER-24013',
        chiefComplaint: 'Chest pain',
        arrivalMethod: 'Walk-in',
        status: 'Under Evaluation',
      },
    },
  ];

  const orders = [
    {
      id: 'ord-9001',
      patientId: 'p-1001',
      orderName: 'CT Head Without Contrast',
      cptCode: '70450',
      modality: 'CT',
      department: 'Radiology',
      orderDateTime: iso(now),
      description: 'Rule out intracranial hemorrhage.',
      status: 'Pending',
      priority: 'Routine',
      findings: '',
      impressions: '',
      testNotes: '',
      techniques: ['CT'],
      chiefComplaint: 'Headache',
      interpretedBy: '',
      imagingDetailDateTime: iso(now),
      lastUpdatedAt: iso(now),
      lastUpdatedBy: 'radiologist1',
      providerName: 'Dr. Jane Smith',
      files: [
        { id: 'f-1', name: 'CT_Head_Images.pdf', type: 'pdf' },
        { id: 'f-2', name: 'CT_Head_Scout.jpg', type: 'image' },
      ],
    },
    {
      id: 'ord-9002',
      patientId: 'p-1002',
      orderName: 'Ultrasound Abdomen',
      cptCode: '76700',
      modality: 'US',
      department: 'Radiology',
      orderDateTime: iso(now),
      description: '',
      status: 'In Progress',
      priority: 'Urgent',
      findings: 'Limited study. Mild fatty liver suspected.',
      impressions: 'Mild hepatic steatosis.',
      testNotes: '',
      techniques: ['Ultrasound'],
      chiefComplaint: 'Abdominal pain',
      interpretedBy: 'Dr. John Williams',
      imagingDetailDateTime: iso(now),
      lastUpdatedAt: iso(now),
      lastUpdatedBy: 'radiologist2',
      providerName: 'Dr. John Williams',
      files: [{ id: 'f-3', name: 'US_Abdomen_Report.pdf', type: 'pdf' }],
    },
    {
      id: 'ord-9003',
      patientId: 'p-1002',
      orderName: 'X-Ray Chest PA/LAT',
      cptCode: '71046',
      modality: 'XR',
      department: 'Radiology',
      orderDateTime: iso(now),
      description: 'Shortness of breath evaluation.',
      status: 'Completed',
      priority: 'Routine',
      findings: 'No acute cardiopulmonary process.',
      impressions: 'No acute findings.',
      testNotes: '',
      techniques: ['X-Ray'],
      chiefComplaint: 'Abdominal pain',
      interpretedBy: 'Dr. John Williams',
      imagingDetailDateTime: iso(now),
      lastUpdatedAt: iso(now),
      lastUpdatedBy: 'radiologist2',
      providerName: 'Dr. John Williams',
      files: [{ id: 'f-4', name: 'CXR_Image.jpg', type: 'image' }],
    },
    {
      id: 'ord-9004',
      patientId: 'p-1003',
      orderName: 'CT Angiography Chest',
      cptCode: '71275',
      modality: 'CT',
      department: 'Radiology',
      orderDateTime: iso(now),
      description: 'Evaluate for pulmonary embolism.',
      status: 'Cancelled',
      priority: 'Stat',
      findings: '',
      impressions: '',
      testNotes: 'Cancelled per physician order.',
      techniques: ['CT'],
      chiefComplaint: 'Chest pain',
      interpretedBy: '',
      imagingDetailDateTime: '',
      lastUpdatedAt: iso(now),
      lastUpdatedBy: 'radiologist1',
      providerName: 'Dr. Jane Smith',
      files: [],
    },
  ];

  return { patients, orders };
}

