export const STATUS_FILTER_OPTIONS = [
  { value: 'all', label: 'All statuses' },
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
];

const TS = '2025-01-15T08:00:00.000Z';

export const HCPCS_STORAGE_KEY = 'hms_hcpcs_codes';
export const HCPCS_SEED_VERSION = 2;

export const HCPCS_LEVEL_OPTIONS = [
  { value: 'all', label: 'All code levels' },
  { value: 'national', label: 'National (A–V)' },
  { value: 'temporary', label: 'Temporary (G, Q, S)' },
  { value: 'drugs', label: 'Drug / biological (J)' },
  { value: 'dme', label: 'DME & supplies (E, K, L)' },
];

export const HCPCS_CATEGORY_OPTIONS = [
  { value: 'all', label: 'All categories' },
  { value: 'transport', label: 'Ambulance & transport' },
  { value: 'drugs', label: 'Drugs & injectables' },
  { value: 'dme', label: 'DME & supplies' },
  { value: 'procedures', label: 'Procedures & screenings' },
  { value: 'vaccines', label: 'Vaccines & immunizations' },
  { value: 'vision', label: 'Vision & hearing' },
  { value: 'temporary', label: 'Temporary / miscellaneous' },
];

export const HCPCS_LEVEL_LABELS = {
  national: 'National',
  temporary: 'Temporary',
  drugs: 'Drug / biological',
  dme: 'DME & supplies',
};

function hcpcsLevelFromCode(code) {
  const c = String(code || '').toUpperCase();
  const letter = c.charAt(0);
  if (letter === 'J') return 'drugs';
  if (['E', 'K', 'L'].includes(letter)) return 'dme';
  if (['G', 'Q', 'S'].includes(letter)) return 'temporary';
  return 'national';
}

export const HCPCS_SEED = [
  {
    id: 'hcpcs-99213',
    code: '99213',
    shortDescription: 'Office visit, established patient, low complexity',
    longDescription:
      'Evaluation and management; established patient office or other outpatient visit, typically 20–29 minutes.',
    category: 'procedures',
    codeLevel: 'national',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0510',
    billable: true,
    internalNotes: 'Common E/M; verify medical necessity and time documentation.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-99214',
    code: '99214',
    shortDescription: 'Office visit, established patient, moderate complexity',
    longDescription:
      'Evaluation and management; established patient, moderate medical decision making.',
    category: 'procedures',
    codeLevel: 'national',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0510',
    billable: true,
    internalNotes: '',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-a0428',
    code: 'A0428',
    shortDescription: 'Ambulance service, BLS, non-emergency',
    longDescription: 'Basic life support ambulance transport, non-emergency.',
    category: 'transport',
    codeLevel: 'national',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0540',
    billable: true,
    internalNotes: 'Requires origin/destination and medical necessity on claim.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-a0425',
    code: 'A0425',
    shortDescription: 'Ambulance mileage, per statute mile',
    longDescription: 'Ground mileage, per statute mile (used with transport base codes).',
    category: 'transport',
    codeLevel: 'national',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0540',
    billable: true,
    internalNotes: 'Bill in conjunction with A0428 or similar base code.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-g0008',
    code: 'G0008',
    shortDescription: 'Administration of influenza virus vaccine',
    longDescription: 'Medicare influenza vaccination administration (seasonal).',
    category: 'vaccines',
    codeLevel: 'temporary',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0771',
    billable: true,
    internalNotes: 'Pair with appropriate vaccine product code.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-g0101',
    code: 'G0101',
    shortDescription: 'Cervical/vaginal cancer screening; pelvic & clinical breast exam',
    longDescription: 'Medicare screening pelvic examination and clinical breast exam.',
    category: 'procedures',
    codeLevel: 'temporary',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0510',
    billable: true,
    internalNotes: 'Screening frequency limits apply per Medicare guidelines.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-j1885',
    code: 'J1885',
    shortDescription: 'Injection, ketorolac tromethamine, per 15 mg',
    longDescription: 'Parental drug; ketorolac tromethamine 15 mg.',
    category: 'drugs',
    codeLevel: 'drugs',
    modifier: '',
    defaultUnits: '15',
    revenueCode: '0636',
    billable: true,
    internalNotes: 'Document units administered; NDC required on claim.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-j1100',
    code: 'J1100',
    shortDescription: 'Injection, dexamethasone sodium phosphate, 1 mg',
    longDescription: 'Dexamethasone sodium phosphate, 1 mg.',
    category: 'drugs',
    codeLevel: 'drugs',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0636',
    billable: true,
    internalNotes: '',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-e0601',
    code: 'E0601',
    shortDescription: 'Continuous positive airway pressure (CPAP) device',
    longDescription: 'CPAP device for obstructive sleep apnea; DME benefit criteria apply.',
    category: 'dme',
    codeLevel: 'dme',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0290',
    billable: true,
    internalNotes: 'Requires sleep study and CMN; rental vs purchase rules apply.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-l3908',
    code: 'L3908',
    shortDescription: 'Wrist hand finger orthosis, custom fabricated',
    longDescription: 'Orthotic device; wrist/hand/finger, custom fabricated.',
    category: 'dme',
    codeLevel: 'dme',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0290',
    billable: true,
    internalNotes: 'Orthotics certification may be required.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-80053',
    code: '80053',
    shortDescription: 'Comprehensive metabolic panel',
    longDescription: 'Clinical laboratory panel; comprehensive metabolic panel (CMP).',
    category: 'procedures',
    codeLevel: 'national',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0301',
    billable: true,
    internalNotes: 'Lab CLIA and ordering provider required.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-71046',
    code: '71046',
    shortDescription: 'Radiologic exam, chest; 2 views',
    longDescription: 'Chest X-ray, two views (frontal and lateral).',
    category: 'procedures',
    codeLevel: 'national',
    modifier: '26',
    defaultUnits: '1',
    revenueCode: '0324',
    billable: true,
    internalNotes: 'Modifier 26 = professional component when billing physician interpretation.',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-v2020',
    code: 'V2020',
    shortDescription: 'Frames, eyeglasses',
    longDescription: 'Vision services; frames for eyeglasses.',
    category: 'vision',
    codeLevel: 'national',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0510',
    billable: false,
    internalNotes: 'Often non-covered except specific vision riders; verify payer policy.',
    isActive: false,
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'hcpcs-q0091',
    code: 'Q0091',
    shortDescription: 'Screening Papanicolaou smear; obtaining, preparing, conveyance',
    longDescription: 'Obtaining, preparing, and conveyance of cervical cytology specimen.',
    category: 'procedures',
    codeLevel: 'temporary',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '0301',
    billable: true,
    internalNotes: '',
    isActive: true,
    createdAt: TS,
    updatedAt: TS,
  },
];

export const HCPCS_CONFIG = {
  storageKey: HCPCS_STORAGE_KEY,
  seedVersion: HCPCS_SEED_VERSION,
  title: 'HCPCS Codes',
  description:
    'Maintain procedure, supply, drug, and service codes used on professional and institutional claims (HCPCS Level II and selected CPT).',
  pageIntro: {
    title: 'About HCPCS in this system',
    bullets: [
      'Level II alphanumeric codes (A–V) cover supplies, drugs, ambulance, DME, and temporary national codes.',
      'Use modifiers and default units to reduce claim edits when interfacing with your billing system.',
      'Mark codes inactive instead of deleting when payers retire or replace a code set.',
    ],
  },
  addLabel: 'Add HCPCS Code',
  searchPlaceholder: 'Search code, description, modifier, revenue code, or notes...',
  codeLabel: 'HCPCS / CPT Code',
  categoryFilterOptions: HCPCS_CATEGORY_OPTIONS,
  categoryFieldOptions: HCPCS_CATEGORY_OPTIONS.filter((o) => o.value !== 'all'),
  secondaryFilterOptions: HCPCS_LEVEL_OPTIONS,
  secondaryFilterKey: 'codeLevel',
  seed: HCPCS_SEED,
  emptyForm: () => ({
    code: '',
    shortDescription: '',
    longDescription: '',
    category: '',
    codeLevel: 'national',
    modifier: '',
    defaultUnits: '1',
    revenueCode: '',
    billable: true,
    internalNotes: '',
    isActive: true,
  }),
  rowToForm: (row) => ({
    code: row?.code || '',
    shortDescription: row?.shortDescription || '',
    longDescription: row?.longDescription || '',
    category: row?.category || '',
    codeLevel: row?.codeLevel || hcpcsLevelFromCode(row?.code),
    modifier: row?.modifier || '',
    defaultUnits: row?.defaultUnits ?? '1',
    revenueCode: row?.revenueCode || '',
    billable: row?.billable !== false,
    internalNotes: row?.internalNotes || '',
    isActive: row?.isActive !== false,
  }),
  formatCategory: (value) => {
    const match = HCPCS_CATEGORY_OPTIONS.find((o) => o.value === value);
    return match?.label || value || '—';
  },
  formatCodeLevel: (value) => HCPCS_LEVEL_LABELS[value] || value || '—',
  inferCodeLevel: hcpcsLevelFromCode,
  getSummaryStats: (items) => {
    const active = items.filter((r) => r.isActive !== false).length;
    const billable = items.filter((r) => r.billable !== false && r.isActive !== false).length;
    const drugs = items.filter((r) => r.codeLevel === 'drugs' || String(r.code).startsWith('J')).length;
    return [
      { label: 'Total codes', value: items.length },
      { label: 'Active', value: active },
      { label: 'Billable (active)', value: billable },
      { label: 'Drug / J codes', value: drugs },
    ];
  },
  columns: [
    { key: 'code', label: 'Code', cellClassName: 'font-mono font-medium' },
    { key: 'shortDescription', label: 'Short description' },
    {
      key: 'codeLevel',
      label: 'Level',
      render: (row, ctx) => ctx.formatCodeLevel(row.codeLevel || ctx.inferCodeLevel(row.code)),
    },
    {
      key: 'category',
      label: 'Category',
      render: (row, ctx) => ctx.formatCategory(row.category),
    },
    {
      key: 'modifier',
      label: 'Mod',
      render: (row) => row.modifier || '—',
    },
    {
      key: 'billable',
      label: 'Billable',
      render: (row) => (row.billable !== false ? 'Yes' : 'No'),
    },
  ],
  viewFields: [
    { key: 'code', label: 'Code' },
    { key: 'shortDescription', label: 'Short description' },
    { key: 'longDescription', label: 'Long description' },
    { key: 'codeLevel', label: 'Code level', format: 'codeLevel' },
    { key: 'category', label: 'Category', format: 'category' },
    { key: 'modifier', label: 'Modifier' },
    { key: 'defaultUnits', label: 'Default units' },
    { key: 'revenueCode', label: 'Revenue code' },
    { key: 'billable', label: 'Billable', format: 'billable' },
    { key: 'internalNotes', label: 'Internal notes' },
    { key: 'isActive', label: 'Status', format: 'status' },
  ],
  formFields: 'hcpcs',
};

export const DIAGNOSIS_STORAGE_KEY = 'hms_diagnosis_codes';
export const DIAGNOSIS_SEED_VERSION = 2;

export const DIAGNOSIS_TYPE_OPTIONS = [
  { value: 'all', label: 'All use types' },
  { value: 'primary', label: 'Primary / principal' },
  { value: 'secondary', label: 'Secondary' },
  { value: 'external', label: 'External cause' },
  { value: 'manifestation', label: 'Manifestation' },
];

export const DIAGNOSIS_CATEGORY_OPTIONS = [
  { value: 'all', label: 'All ICD-10 chapters' },
  { value: 'infectious', label: 'A00–B99 Infectious & parasitic' },
  { value: 'neoplasm', label: 'C00–D49 Neoplasms' },
  { value: 'endocrine', label: 'E00–E89 Endocrine & metabolic' },
  { value: 'mental', label: 'F01–F99 Mental & behavioral' },
  { value: 'circulatory', label: 'I00–I99 Circulatory' },
  { value: 'respiratory', label: 'J00–J99 Respiratory' },
  { value: 'digestive', label: 'K00–K95 Digestive' },
  { value: 'musculoskeletal', label: 'M00–M99 Musculoskeletal' },
  { value: 'injury', label: 'S00–T88 Injury & poisoning' },
  { value: 'symptoms', label: 'R00–R99 Symptoms & signs' },
  { value: 'factors', label: 'Z00–Z99 Factors influencing health' },
];

export const DIAGNOSIS_TYPE_LABELS = {
  primary: 'Primary / principal',
  secondary: 'Secondary',
  external: 'External cause',
  manifestation: 'Manifestation',
};

export const DIAGNOSIS_SEED = [
  {
    id: 'dx-z0000',
    code: 'Z00.00',
    description: 'Encounter for general adult medical examination without abnormal findings',
    category: 'factors',
    codeType: 'primary',
    chronic: false,
    billablePrimary: true,
    internalNotes: 'Common preventive visit principal diagnosis when no issues found.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-j069',
    code: 'J06.9',
    description: 'Acute upper respiratory infection, unspecified',
    category: 'respiratory',
    codeType: 'primary',
    chronic: false,
    billablePrimary: true,
    internalNotes: 'Use specificity (J06.0–J06.9) when documentation supports.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-j459',
    code: 'J45.909',
    description: 'Unspecified asthma, uncomplicated',
    category: 'respiratory',
    codeType: 'primary',
    chronic: true,
    billablePrimary: true,
    internalNotes: 'Consider more specific asthma codes when severity documented.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-e119',
    code: 'E11.9',
    description: 'Type 2 diabetes mellitus without complications',
    category: 'endocrine',
    codeType: 'primary',
    chronic: true,
    billablePrimary: true,
    internalNotes: 'Add complication codes (E11.65, etc.) when present.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-e785',
    code: 'E78.5',
    description: 'Hyperlipidemia, unspecified',
    category: 'endocrine',
    codeType: 'secondary',
    chronic: true,
    billablePrimary: true,
    internalNotes: '',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-i10',
    code: 'I10',
    description: 'Essential (primary) hypertension',
    category: 'circulatory',
    codeType: 'primary',
    chronic: true,
    billablePrimary: true,
    internalNotes: 'Most common primary hypertension code.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-i2510',
    code: 'I25.10',
    description: 'Atherosclerotic heart disease of native coronary artery without angina pectoris',
    category: 'circulatory',
    codeType: 'secondary',
    chronic: true,
    billablePrimary: true,
    internalNotes: '',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-m545',
    code: 'M54.5',
    description: 'Low back pain',
    category: 'musculoskeletal',
    codeType: 'primary',
    chronic: false,
    billablePrimary: true,
    internalNotes: 'Specify chronic (M54.50) vs acute when documented.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-f411',
    code: 'F41.1',
    description: 'Generalized anxiety disorder',
    category: 'mental',
    codeType: 'primary',
    chronic: true,
    billablePrimary: true,
    internalNotes: 'Behavioral health billing rules may apply.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-n390',
    code: 'N39.0',
    description: 'Urinary tract infection, site not specified',
    category: 'infectious',
    codeType: 'primary',
    chronic: false,
    billablePrimary: true,
    internalNotes: '',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-k219',
    code: 'K21.9',
    description: 'Gastro-esophageal reflux disease without esophagitis',
    category: 'digestive',
    codeType: 'secondary',
    chronic: true,
    billablePrimary: true,
    internalNotes: '',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-s72001a',
    code: 'S72.001A',
    description: 'Fracture of unspecified part of neck of right femur, initial encounter',
    category: 'injury',
    codeType: 'primary',
    chronic: false,
    billablePrimary: true,
    internalNotes: '7th character (A/D/S) required for injury codes; train staff on encounter type.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-t1490',
    code: 'T14.90XA',
    description: 'Injury, unspecified, initial encounter',
    category: 'injury',
    codeType: 'external',
    chronic: false,
    billablePrimary: false,
    internalNotes: 'Avoid as primary when possible; lacks specificity.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-r079',
    code: 'R07.9',
    description: 'Chest pain, unspecified',
    category: 'symptoms',
    codeType: 'primary',
    chronic: false,
    billablePrimary: true,
    internalNotes: 'Cardiac workup documentation may affect medical necessity.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-c50912',
    code: 'C50.912',
    description: 'Malignant neoplasm of unspecified site of left female breast',
    category: 'neoplasm',
    codeType: 'primary',
    chronic: true,
    billablePrimary: true,
    internalNotes: 'Oncology pathways; laterality and site specificity critical.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
  {
    id: 'dx-z87891',
    code: 'Z87.891',
    description: 'Personal history of nicotine dependence',
    category: 'factors',
    codeType: 'secondary',
    chronic: true,
    billablePrimary: true,
    internalNotes: 'History code; not usually principal for acute visit.',
    isActive: true,
    effectiveFrom: '2015-10-01',
    effectiveTo: '',
    createdAt: TS,
    updatedAt: TS,
  },
];

export const DIAGNOSIS_CONFIG = {
  storageKey: DIAGNOSIS_STORAGE_KEY,
  seedVersion: DIAGNOSIS_SEED_VERSION,
  title: 'Diagnosis Codes',
  description:
    'Maintain ICD-10-CM diagnosis codes for problem lists, encounter diagnoses, and claim submission.',
  pageIntro: {
    title: 'About ICD-10-CM in this system',
    bullets: [
      'Codes support principal, secondary, external cause, and manifestation roles on the claim.',
      'Use effective dates when payers publish annual ICD-10 updates or code freezes.',
      'Chronic and billable-as-primary flags help front-desk and coding staff pick valid combinations.',
    ],
  },
  addLabel: 'Add Diagnosis Code',
  searchPlaceholder: 'Search ICD-10 code, description, chapter, or notes...',
  codeLabel: 'ICD-10-CM Code',
  categoryFilterOptions: DIAGNOSIS_CATEGORY_OPTIONS,
  categoryFieldOptions: DIAGNOSIS_CATEGORY_OPTIONS.filter((o) => o.value !== 'all'),
  secondaryFilterOptions: DIAGNOSIS_TYPE_OPTIONS,
  secondaryFilterKey: 'codeType',
  seed: DIAGNOSIS_SEED,
  emptyForm: () => ({
    code: '',
    description: '',
    category: '',
    codeType: 'primary',
    chronic: false,
    billablePrimary: true,
    internalNotes: '',
    isActive: true,
    effectiveFrom: '',
    effectiveTo: '',
  }),
  rowToForm: (row) => ({
    code: row?.code || '',
    description: row?.description || '',
    category: row?.category || '',
    codeType: row?.codeType || 'primary',
    chronic: row?.chronic === true,
    billablePrimary: row?.billablePrimary !== false,
    internalNotes: row?.internalNotes || '',
    isActive: row?.isActive !== false,
    effectiveFrom: row?.effectiveFrom || '',
    effectiveTo: row?.effectiveTo || '',
  }),
  formatCategory: (value) => {
    const match = DIAGNOSIS_CATEGORY_OPTIONS.find((o) => o.value === value);
    return match?.label || value || '—';
  },
  formatCodeType: (value) => DIAGNOSIS_TYPE_LABELS[value] || value || '—',
  getSummaryStats: (items) => {
    const active = items.filter((r) => r.isActive !== false).length;
    const chronic = items.filter((r) => r.chronic === true).length;
    const primary = items.filter((r) => r.codeType === 'primary').length;
    return [
      { label: 'Total codes', value: items.length },
      { label: 'Active', value: active },
      { label: 'Chronic conditions', value: chronic },
      { label: 'Primary-type codes', value: primary },
    ];
  },
  columns: [
    { key: 'code', label: 'ICD-10 Code', cellClassName: 'font-mono font-medium' },
    { key: 'description', label: 'Description' },
    {
      key: 'codeType',
      label: 'Use type',
      render: (row, ctx) => ctx.formatCodeType(row.codeType),
    },
    {
      key: 'category',
      label: 'Chapter',
      render: (row, ctx) => ctx.formatCategory(row.category),
    },
    {
      key: 'chronic',
      label: 'Chronic',
      render: (row) => (row.chronic ? 'Yes' : 'No'),
    },
    {
      key: 'effectiveFrom',
      label: 'Effective',
      render: (row) => row.effectiveFrom || '—',
    },
  ],
  viewFields: [
    { key: 'code', label: 'ICD-10-CM Code' },
    { key: 'description', label: 'Description' },
    { key: 'codeType', label: 'Use type', format: 'codeType' },
    { key: 'category', label: 'ICD-10 chapter', format: 'category' },
    { key: 'chronic', label: 'Chronic condition', format: 'chronic' },
    { key: 'billablePrimary', label: 'Billable as primary', format: 'billable' },
    { key: 'effectiveFrom', label: 'Effective from' },
    { key: 'effectiveTo', label: 'Effective to' },
    { key: 'internalNotes', label: 'Coding notes' },
    { key: 'isActive', label: 'Status', format: 'status' },
  ],
  formFields: 'diagnosis',
};
